### ISSUE TITLE
Rename config parameters in book service

### ISSUE THREAD

**Issue by Feyzanrs** [octoposprime/op-be-book#32]
In the book service's configuration files (```internal.yml, internal_test.yml, and internal_local.yml```), we need to update the naming conventions for certain parameters to better reflect their usage:

- Change `dlr_host` to `book_host`
- Change `dlr_port` to `book_port`

**The changes will be merged into the first/team/2/create-book branch first. Therefore, set the base branch of the pull request as first/team/2/create-book.**

**Comment by Feyzanrs** [comment]
Do we need to change it like this?  I couldn't be sure. @Sddilora

**Comment by Sddilora** [comment]
of course

**Comment by Sddilora** [comment]
of course
